use clap::{Parser, Subcommand};
use client_sdk::helpers::risc0::Risc0Prover;
use contract_farcaster_identity::FarcasterIdentityContractState;
use ed25519_dalek::{SigningKey, Signer, VerifyingKey};
use rand::rngs::OsRng;
use sdk::api::APIRegisterContract;
use sdk::BlobTransaction;
use sdk::ProofTransaction;
use sdk::{ContractInput, Digestable};
use std::fs::File;
use std::io::Write;

// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
use methods_farcaster_identity::{GUEST_ELF, GUEST_ID};

#[derive(Parser)]
#[command(author, version, about, long_about = None)]
#[command(propagate_version = true)]
struct Cli {
    #[command(subcommand)]
    command: Commands,

    #[clap(long, short)]
    reproducible: bool,

    #[arg(long, default_value = "http://localhost:4321")]
    pub host: String,

    #[arg(long, default_value = "farcaster_identity")]
    pub contract_name: String,
}

#[derive(Subcommand)]
enum Commands {
    RegisterContract {},
    RegisterIdentity {
        address: String,
        fid: u64,
        #[arg(long)]
        app_fid: Option<u64>,
        #[arg(long)]
        username: Option<String>,
    },
    VerifyIdentity {
        address: String,
        nonce: u32,
        message: String,
    },
    GenerateKeyPair {
        #[arg(long)]
        output_file: Option<String>,
    },
    GetSignerQrCode {
        #[arg(long)]
        app_fid: u64,
    },
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    let cli = Cli::parse();

    let client = client_sdk::rest_client::NodeApiHttpClient::new(cli.host).unwrap();

    let contract_name = &cli.contract_name;

    let prover = Risc0Prover::new(GUEST_ELF);

    match cli.command {
        Commands::RegisterContract {} => {
            // Build initial state of contract
            let initial_state = FarcasterIdentityContractState::new();
            println!("Initial state: {:?}", initial_state);

            // Send the transaction to register the contract
            let res = client
                .register_contract(&APIRegisterContract {
                    verifier: "risc0".into(),
                    program_id: sdk::ProgramId(sdk::to_u8_array(&GUEST_ID).to_vec()),
                    state_digest: initial_state.as_digest(),
                    contract_name: contract_name.clone().into(),
                })
                .await
                .unwrap();

            println!("✅ Register contract tx sent. Tx hash: {}", res);
        }
        Commands::RegisterIdentity { address, fid, app_fid, username } => {
            // Fetch the initial state from the node
            let initial_state: FarcasterIdentityContractState = client
                .get_contract(&contract_name.clone().into())
                .await
                .unwrap()
                .state
                .into();

            println!("Initial state {:?}", initial_state.clone());
            
            // Generate a new Ed25519 key pair for this identity
            let mut csprng = OsRng;
            let signing_key = SigningKey::generate(&mut csprng);
            let verifying_key = signing_key.verifying_key();
            
            // Convert the public key to hex string
            let public_key_hex = hex::encode(verifying_key.as_bytes());
            
            // Save the private key to a file for the user
            let private_key_file = format!("farcaster_key_{}.json", address);
            let key_data = serde_json::json!({
                "address": address,
                "fid": fid,
                "private_key": hex::encode(signing_key.to_bytes()),
                "public_key": public_key_hex
            });
            
            let mut file = File::create(&private_key_file)?;
            file.write_all(serde_json::to_string_pretty(&key_data).unwrap().as_bytes())?;
            println!("✅ Key pair saved to {}", private_key_file);
            
            // Create the identity data
            let identity_data = serde_json::json!({
                "fid": fid,
                "public_key": public_key_hex,
                "app_fid": app_fid,
                "username": username
            });

            // Build the blob transaction
            let action = sdk::identity_provider::IdentityAction::RegisterIdentity {
                account: address.clone(),
            };
            
            let blobs = vec![sdk::Blob {
                contract_name: contract_name.clone().into(),
                data: sdk::BlobData(
                    bincode::encode_to_vec(action, bincode::config::standard())
                        .expect("failed to encode BlobData"),
                ),
            }];

            // Generate the proof for registering the identity
            let proof = prover
                .prove(ContractInput {
                    initial_state: initial_state.as_digest(),
                    blobs: blobs.clone(),
                    private_input: identity_data.to_string().into_bytes(),
                })
                .unwrap();

            // Create and submit the proof transaction
            let tx = ProofTransaction::new(vec![sdk::Transaction::Blob(BlobTransaction {
                txid: client_sdk::helpers::compute_blob_txid(&blobs, None),
                blobs,
                proof: Some(proof),
            })]);

            let res = client.submit_transaction(&tx).await.unwrap();
            println!("✅ Register identity tx sent. Tx hash: {}", res);
        }
        Commands::VerifyIdentity { address, nonce, message } => {
            // Fetch the initial state from the node
            let initial_state: FarcasterIdentityContractState = client
                .get_contract(&contract_name.clone().into())
                .await
                .unwrap()
                .state
                .into();

            // Get the signature from the user 
            println!("Please enter the signature for message '{}' (hex format):", message);
            let mut signature_hex = String::new();
            std::io::stdin().read_line(&mut signature_hex)?;
            let signature_hex = signature_hex.trim();

            // Create verification data
            let verification_data = serde_json::json!({
                "message": message,
                "signature": signature_hex
            });

            // Build the blob transaction
            let action = sdk::identity_provider::IdentityAction::VerifyIdentity {
                account: address.clone(),
                nonce,
            };
            
            let blobs = vec![sdk::Blob {
                contract_name: contract_name.clone().into(),
                data: sdk::BlobData(
                    bincode::encode_to_vec(action, bincode::config::standard())
                        .expect("failed to encode BlobData"),
                ),
            }];

            // Generate the proof for verifying the identity
            let proof = prover
                .prove(ContractInput {
                    initial_state: initial_state.as_digest(),
                    blobs: blobs.clone(),
                    private_input: verification_data.to_string().into_bytes(),
                })
                .unwrap();

            // Create and submit the proof transaction
            let tx = ProofTransaction::new(vec![sdk::Transaction::Blob(BlobTransaction {
                txid: client_sdk::helpers::compute_blob_txid(&blobs, None),
                blobs,
                proof: Some(proof),
            })]);

            let res = client.submit_transaction(&tx).await.unwrap();
            println!("✅ Verify identity tx sent. Tx hash: {}", res);
        }
        Commands::GenerateKeyPair { output_file } => {
            // Generate a new Ed25519 key pair
            let mut csprng = OsRng;
            let signing_key = SigningKey::generate(&mut csprng);
            let public_key = signing_key.verifying_key();
            
            // Convert keys to hex format
            let private_key_hex = hex::encode(signing_key.to_bytes());
            let public_key_hex = hex::encode(public_key.as_bytes());
            
            println!("Generated Ed25519 Key Pair:");
            println!("Public Key: {}", public_key_hex);
            
            // Save to file if requested
            if let Some(filename) = output_file {
                let key_data = serde_json::json!({
                    "private_key": private_key_hex,
                    "public_key": public_key_hex
                });
                
                let mut file = File::create(&filename)?;
                file.write_all(serde_json::to_string_pretty(&key_data).unwrap().as_bytes())?;
                println!("✅ Key pair saved to {}", filename);
            } else {
                println!("Private Key: {}", private_key_hex);
                println!("(Note: Keep your private key secure!)");
            }
        }
        Commands::GetSignerQrCode { app_fid } => {
            // Generate a new Ed25519 key pair
            let mut csprng = OsRng;
            let signing_key = SigningKey::generate(&mut csprng);
            let public_key = signing_key.verifying_key();
            
            // Convert public key to hex for the request
            let public_key_hex = format!("0x{}", hex::encode(public_key.as_bytes()));
            
            // Set deadline (24 hours from now)
            let deadline = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_secs() + 86400;
            
            println!("This simulates the Farcaster signer QR code flow");
            println!("In a real implementation, you would:");
            println!("1. Generate an EIP-712 signature using the app FID: {}", app_fid);
            println!("2. Send a POST request to https://api.warpcast.com/v2/signed-key-requests");
            println!("3. Receive and display a QR code with the deeplink URL");
            println!();
            println!("Request would include:");
            println!("Key: {}", public_key_hex);
            println!("App FID: {}", app_fid);
            println!("Deadline: {}", deadline);
            
            // Save private key to file for later use
            let key_file = format!("farcaster_app_key_{}.json", app_fid);
            let key_data = serde_json::json!({
                "app_fid": app_fid,
                "private_key": hex::encode(signing_key.to_bytes()),
                "public_key": hex::encode(public_key.as_bytes())
            });
            
            let mut file = File::create(&key_file)?;
            file.write_all(serde_json::to_string_pretty(&key_data).unwrap().as_bytes())?;
            println!("✅ App key saved to {}", key_file);
            
            // Create a mock QR code with dummy farcaster deeplink
            let mock_deeplink = format!("farcaster://signed-key-request?token=mock-token-{}", app_fid);
            let qr_code = qrcode::QrCode::new(mock_deeplink.clone())?;
            let qr_string = qr_code.render::<char>().quiet_zone(false).build();
            
            println!("\nSample QR Code (Mock):");
            println!("{}", qr_string);
            println!("\nDeeplink URL: {}", mock_deeplink);
        }
    }

    Ok(())
}