// Generated code to embed the ELF binary and ImageID

// This file is automatically generated when the project is built.

// Definitions of GUEST_ELF and GUEST_ID
// We're importing them but the actual values are set at build time
include!(concat!(env!("OUT_DIR"), "/methods.rs"));